### ISSUE TITLE
Cannot select more than one searched items

### ISSUE THREAD

**Issue by vladdvs** [alexandernst/angular-multi-select#101]
After selecting first searched item serching results will be lost(but searching string will be there)

**Comment by alexandernst** [comment]
Is your output model pointing to the input model or to some nested part of
it? I can't think of any other reason why this would happen.

Can you post an example of the bug?

**Comment by vladdvs** [comment]
example http://alexandernst.github.io/angular-multi-select/#/main

**Comment by vladdvs** [comment]
![animation](https://cloud.githubusercontent.com/assets/1526857/15599653/0b2a6bee-2428-11e6-8bee-c2f8d1158e87.gif)
