### ISSUE TITLE
ReferenceError: loki is not defined

### ISSUE THREAD

**Issue by abhith** [alexandernst/angular-multi-select#106]
I tried the 7.4.6 version with the example in the doc _"Field(s) of each selected item"_, but i get this error "**ReferenceError: loki is not defined**"

Let me know if more details required.

**Comment by alexandernst** [comment]
Indeed, I just saw there is a missing line. You must include Loki also!

`https://cdnjs.com/libraries/lokijs/1.3.16`

**Comment by alexandernst** [comment]
I already updated `http://alexandernst.github.io/angular-multi-select/#/getting-started`
