### ISSUE TITLE
if two values have same id , one of the id is getting overwritten

### ISSUE THREAD

**Issue by prashasti4** [alexandernst/angular-multi-select#112]
sample json:
[{
	"id": "-1",
	"text": "ALL SCHEDULES",
	"value": "ALL SCHEDULES",
	"checked": true,
	"open": true,
	"children": [{
		"id": "140007453-B",
		"value": "ME – STR",
		"text": "ME – STR",
		"open": true,
		"checked": true,
		"children": [{
			"id": "140002324",
			"value": "CARE(CARE)",
			"text": "CARE (CARE)",
			"open": true,
			"checked": true
		}, {
			"id": "140006953",
			"value": "CLAIM",
			"text": "CLAIM",
			"open": true,
			"checked": true
		}, {
			"id": "140004457",
			"value": "HOLD(NS)",
			"text": "HOLD(NS)",
			"open": true,
			"checked": true
		}, {
			"id": "140004022",
			"value": "ON  (NOPCS)",
			"text": "ON (NOPCS)",
			"open": true,
			"checked": true
		}]
	}, {
		"id": "140007460",
		"value": "THIRD",
		"text": "THIRD",
		"open": true,
		"checked": true,
		"children": [{
			"id": "140007920",
			"value": "2NDINSURANCE",
			"text": "2NDINSURANCE",
			"open": true,
			"checked": true
		}, {
			"id": "140006953",
			"value": "CLAIM",
			"text": "CLAIM",
			"open": true,
			"checked": true
		}, {
			"id": "140004763",
			"value": "CONTRACTED",
			"text": "CONTRACTED",
			"open": true,
			"checked": true
		}, {
			"id": "140270238",
			"value": " (DERA)",
			"text": "(DERA)",
			"open": true,
			"checked": true
		}, {
			"id": "140009985",
			"value": "E.C",
			"text": "E.C",
			"open": true,
			"checked": true
		}]
	}]
}]

In  this JSON CLAIM (id:140006953) repeating twice i.e in two different parents, because of which it is over writing the id of one of the CLAIM with some random id,
How Can I fix this?

**Comment by alexandernst** [comment]
This is an expected behaviour. An ID, as per it's name, is an unique identifier. You should fix your data.
