### ISSUE TITLE
Doesn't close when clicking outside

### ISSUE THREAD

**Issue by DonovanCharpin** [alexandernst/angular-multi-select#13]
Hi,

I have an issue, when I click outside the dropdown, it doesn't close.

Thanks in advance

**Comment by alexandernst** [comment]
@Donovan-Ensicaen Have you added the `angular-multi-select-mouse-trap angular-multi-select-key-trap` elements in your document? Please check [getting started](http://alexandernst.github.io/angular-multi-select/#/getting-started)

**Comment by DonovanCharpin** [comment]
Thanks for your answer but I have two angular-multi-select in the page and when I click to the next element, the last element doesn't close.

**Comment by DonovanCharpin** [comment]
I think the problem comes from 

```
$scope.stopListeningMouseEvents = $scope.$on('angular-multi-select-click', function(msg, obj) {
    var inside = false;
    angular.forEach($(obj.event.target).parents(), function(parent) {
        if(inside === true) return;
        if($(parent).attr("angular-multi-select") !== undefined) {
            inside = true;
        }
    });
    if(inside === false){
        $scope.visible = false;
        $scope.$apply();
    }
});
```

In this condition, it checks an attribute which is not unique for each element

```
if($(parent).attr("angular-multi-select") !== undefined) {
       inside = true;
}
```

**Comment by alexandernst** [comment]
I'm having trouble reproducing your issue. Here is a plunkr with 2 multiselects, both are working fine (as far as I can tell). http://plnkr.co/edit/6bjW35D3W1dTGQz9kNSn?p=preview

Can you point me to the issue?

**Comment by DonovanCharpin** [comment]
The plunker code doesn't work for me using safari or chrome. If you click on the second element and then you click on the first, the second element is still opened, isn't it?

**Comment by alexandernst** [comment]
Correct. Should it get closed?

**Comment by alexandernst** [comment]
Yeah, after having a thought about it, yes, it does make sense to close all other widgets before opening a new one. Ok, let me fix it

**Comment by DonovanCharpin** [comment]
Thanks for your reactivity :)

**Comment by alexandernst** [comment]
Fixed :) http://plnkr.co/edit/6bjW35D3W1dTGQz9kNSn?p=preview

**Comment by DonovanCharpin** [comment]
Thank you guy :)
