### ISSUE TITLE
Two way binding on the output

### ISSUE THREAD

**Issue by DonovanCharpin** [alexandernst/angular-multi-select#17]
Hi,

It could be great if the output-model would bind in the two way. If I clear my model, I would like the directive unselect all entries in the UI.

Thanks in advance

**Comment by alexandernst** [comment]
That doesn't sound reasonable. The output model is, as it's name suggest, an output data. It shouldn't interact with the widget. If you want to unselect all items, do it using the input model.

**Comment by DonovanCharpin** [comment]
It makes sense. I'm going to fix my problem. Thanks

**Comment by alexandernst** [comment]
;)

Anyways, I'm planning on adding some helpers to the API. A few methods that would let you (un)select all or an item by ID, programatically. Expect it by the end of the week.

**Comment by DonovanCharpin** [comment]
ok, cool :)
