### ISSUE TITLE
output-model getting updated after on-item-click callback is triggered

### ISSUE THREAD

**Issue by raphaelhudvoy** [alexandernst/angular-multi-select#22]
Hi,

I need to call a function every time an item is clicked. This function needs to have the list of the selected item from the multi-select and is triggered by on-item-click directive. However, the output-model gets updated only after the callback function have been called. 

I think the output model should be updated before the callback is triggered.

**Comment by alexandernst** [comment]
Nice catch. I'll try to close as many issues as I can in tonight's sprint.

**Comment by alexandernst** [comment]
Will tag and release on npm in a few hours.

**Comment by raphaelhudvoy** [comment]
Thanks!!!!
