### ISSUE TITLE
Output filter does not contain pre-selected input

### ISSUE THREAD

**Issue by raphaelhudvoy** [alexandernst/angular-multi-select#23]
Hi,

when I set the checked property to true in the input-model, the output-model does not update until the user select an other item.

ex: 
    $scope.inputmodel= [
        {   name: "{{row.name}}",   checked: true   }
    {   name: "{{row.name}}",   checked: true   }
    {   name: "{{row.name}}",   checked: false}
    ];

the output model stay empty ( [] ).

Thanks 
Raph

**Comment by alexandernst** [comment]
Will fix in a minute.

**Comment by raphaelhudvoy** [comment]
awesome!

**Comment by alexandernst** [comment]
@raphaelhudvoy I'm testing this right now, but it's working here. Are you sure you're using the latest version?

**Comment by raphaelhudvoy** [comment]
Sorry for that! Works fine now after updating to the latest version. Thank a lot for taking time

**Comment by alexandernst** [comment]
No problem ;)
