### ISSUE TITLE
Relation to isteven?

### ISSUE THREAD

**Issue by aciccarello** [alexandernst/angular-multi-select#41]
What is the relationship between this project and [isteven/angular-multi-select](https://github.com/isteven/angular-multi-select)? Is this a fork and why is there no reference to @isteven?

**Comment by alexandernst** [comment]
@aciccarello This project started as a fork of isteven's project. That said, I soon realized his code was so buggy and limited that I had to rewrite it from 0. And because of that, there are no references to isteven's project.

If you don't have any further questions, please close this issue.

**Comment by aciccarello** [comment]
Okay I'll close the issue. I just raised it because I recognized that the two were linked but couldn't find any references to the other.

Personally I think it would be responsible to at least mention isteven as the idea originator even if you have redone everything.

**Comment by alexandernst** [comment]
@aciccarello Don't get confused. isteven isn't the first guy who created a multiselect dropdown. If something, I should rather link to the very first multiselect dropdown. And even then, ¿why? What do you think that would be like?

```
This project has no relation whatsoever with isteven/angular-multi-select, my code is better/cleaner/easier to use, but both projects kind of do the same thing
```

?

**Comment by aciccarello** [comment]
I was more so referencing the similarities in the styling of the multi-select and the documentation (not the idea of multiple selections). I understand you have reworked everything and it's probably better, but I wouldn't say there is no relation.
