### ISSUE TITLE
Menu items repeat when using the search box

### ISSUE THREAD

**Issue by abyrne85** [alexandernst/angular-multi-select#42]
I'm trying to implement the search area on the drop-down.  Initially the search functionality works fine, but when you start removing characters from the search field, the list items in the drop down start behaving erratically.  Some items are being repeated, while other items are being removed from the list.  

Here is a plunkr to demonstrate the issue : http://plnkr.co/edit/uPvfSJ8IngeFFGAcHvMd?p=preview

I would imagine this is an error on how I'm implementing the search field, rather than a bug in the directive.  Either way, if you have any suggestions I would love to hear them.

Thanks

**Comment by alexandernst** [comment]
This is bug https://github.com/alexandernst/angular-multi-select/issues/35 which got fixed in the next version. Please try to use latest version if possible.

**Comment by abyrne85** [comment]
Just upgraded and everything works perfectly.  Thanks for the help, and thanks for putting together a really helpful directive.

**Comment by alexandernst** [comment]
You're welcome ;)
