### ISSUE TITLE
bower packaging

### ISSUE THREAD

**Issue by jtbdevelopment** [alexandernst/angular-multi-select#43]
is there some reason you are not using npm/bower correctly and putting all your dependencies in the bower.json and correct publish details in there?  If you did so this package would work properly like all other bower packages for client side where a) it auto updates your index.html and b) has the dependencies built in?

I have forked and will look at fixing but unclear why this wasn't done in first place.  the npm packages.json should just be containing what you need to run the build and test harnesses.

**Comment by alexandernst** [comment]
No reason, just forgot to port the package.json devDeps to the bower.json file. I'll accept your PR when you're ready.

**Comment by jtbdevelopment** [comment]
I will pull shortly, I also need to make angular 1.4 updates so I did not actually test the install to a clean project (this section in bower.json)

  "main": [
    "dist/angular-multi-select.js",
    "dist/angular-multi-select"
  ],

**Comment by alexandernst** [comment]
Fixed by #44
