### ISSUE TITLE
Filter doesn't work for simple cases

### ISSUE THREAD

**Issue by hhinch212** [alexandernst/angular-multi-select#51]
The filtering doesn't work unless you are doing Grouping.  For examples see the Minimal Demo or the Dynamic Update demo.  If you type in the search box it doesn't limit what you see.

**Comment by alexandernst** [comment]
The filtering isn't working in those examples because it's not activated (because the purpose of the minimal and the dynamic demos isn't about showing how filtering works).

**Comment by alexandernst** [comment]
Please close this issue if you don't have any further questions about this specific problem.

**Comment by hhinch212** [comment]
Sorry I was missing the search-property options
