### ISSUE TITLE
Possible to update input model instead of using new output model

### ISSUE THREAD

**Issue by corydorning** [alexandernst/angular-multi-select#54]
I'm trying to figure out the best way to provide your directive with an input model and have that model updated instead of generating a new output model that only contains the 'selected' items. 

Quite possible i missed this in the docs, so wanted to see if this was possible.

**Comment by alexandernst** [comment]
Can't be done, by design. An input model is, as it's name suggests, an input value. It can't be modified. Anyways, I'm sure you can do what you're trying to do with a couple of lines of code using the output model.
