### ISSUE TITLE
toggle-children doesn't work

### ISSUE THREAD

**Issue by alexandernst** [alexandernst/angular-multi-select#65]
Dimitar Dimitrov said:

Hi, I use your multiselect dropdown(https://github.com/alexandernst/angular-multi-select), but when I set "toggle-children" to "false" nothing is change. And when I click on children, the parent is selected too. What I'm doing wrong? Here is my example:

```
<div
        angular-multi-select
        input-model="webBrowsersGrouped"
        output-model="outputBrowsers"
        item-label="<[ icon ]> <[ name ]>"
        tick-property="checked"
        group-property="sub"
        toggle-children="false"
        >
</div>
```

**Comment by alexandernst** [comment]
Are you using master or the latest released version? This change hasn't been released yet (so you must use master for now).

**Comment by ddimitrov123** [comment]
I use version 5.4.1

**Comment by alexandernst** [comment]
So, there you go. You must use master (for now) until I release a new version.

**Comment by alexandernst** [comment]
Please close this issue when you have switched to master and tested your code.

**Comment by ddimitrov123** [comment]
Now I switched to version 5.5.3, but the problem is still there.

**Comment by alexandernst** [comment]
You must use <b>master</b>. This means that you can't use a released version, you must gran [this](https://github.com/alexandernst/angular-multi-select/blob/master/src/angular-multi-select.js) file directly.

**Comment by ddimitrov123** [comment]
This way it works, thanks for help, you can close this issue.

**Comment by alexandernst** [comment]
Remember to switch to the latest stable version once I have released this feature. You shouldn't be using master in production.

**Comment by ddimitrov123** [comment]
When this feature will be released with bower/npm? I didn't see a configuration when a parent is selected all his children to be selected, but when a single child is slected its parent should not to be selected. Am I missing it or it is not part of the directive and if not are you planing to make such configuration.

**Comment by alexandernst** [comment]
I'm planning to release this tomorrow at some point of the day, or sunday max.

**Comment by alexandernst** [comment]
@ddimitrov123 5.5.4 was just released. ;)
