### ISSUE TITLE
Provider for global configuration

### ISSUE THREAD

**Issue by salvadormarcos** [alexandernst/angular-multi-select#74]
I would like to have a angular provider to set global configs. I could set the property "translation" in provider.

**Comment by alexandernst** [comment]
Haven't forgotten about that. I'm getting to it, I just merged v6

**Comment by alexandernst** [comment]
Implemented in https://github.com/alexandernst/angular-multi-select/commit/ea38c3707e213faaa90483ef299961e1493bf2a2
