### ISSUE TITLE
TypeError: Cannot set property 'allChecked' of null

### ISSUE THREAD

**Issue by my9074** [alexandernst/angular-multi-select#75]
I use search , When dosn't search any item, The console show :Cannot set property 'allChecked' of null.

Related to Angular version? I used Angular 1.4.6

**Comment by alexandernst** [comment]
Can you tell me what version of angular-multi-select are you using?

**Comment by brettskermetzger** [comment]
I ran into this issue as well. I found two instances of our input model being declared in the controller. So it was being overwritten after pushing the data into it. 

Pretty much user error. Nothing wrong with the multi-select.
