### ISSUE TITLE
Does not work in IE11 with Array.prototype.findIndex polyfill defined

### ISSUE THREAD

**Issue by fifonik** [alexandernst/angular-multi-select#77]
It does not work in IE11 if [Array.prototype.findIndex polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/findIndex#Polyfill) defined.

http://plnkr.co/edit/H4HTjvp80WEefqUPzpmG?p=preview
Fx -- OK
IE11 -- error 
TypeError: Unable to get property '' of undefined or null reference
at $scope._isHidden (angular-multi-select.js:538:5)

Comment out Array.prototype.findIndex polyfill in app.js and it will works fine in IE11 as well.

**Comment by alexandernst** [comment]
I'm currently working on v6, which will hopefully fix tons of possible bugs and greatly improve performance. Can this wait for a few days until I finish v6?

**Comment by fifonik** [comment]
Thanks for your answer.
I'll wait for a few days.

**Comment by alexandernst** [comment]
I just merged v6. Docs are still missing, but you can check the specs, those are very nice (until I finish the docs).
