### ISSUE TITLE
Click on the label to toggle (parent) or select the element

### ISSUE THREAD

**Issue by JihadMotii-REISys** [alexandernst/angular-multi-select#84]
Is there a way to toggle a parent element or select an element by clicking on the title instead of "X" or ">" to toggle a parent element ?

Thanks

**Comment by alexandernst** [comment]
By toggle you mean toggle the open/closed state or toggle the
checked/unchecked state? In any case, it's not possible with the current
code as-is, but the patch to allow that is a single line modification. Let
me see if I can do it this afternoon.

**Comment by alexandernst** [comment]
Done, please have a look at http://alexandernst.github.io/angular-multi-select/#/mods

**Comment by JihadMotii-REISys** [comment]
@alexandernst This works great ! but I noticed that I can't use them both when I include them ?

**Comment by alexandernst** [comment]
One of the 2 available mods makes a click on the item's label open the
item, while the other one makes the item being clicked to toggle the
un/checked state. How would you expect them both to work at the same time?

**Comment by JihadMotii-REISys** [comment]
I was thinking for nodes, the toggle state should be applied and for leaf, the check/uncheck state should be applied. What do you think ?

**Comment by alexandernst** [comment]
Ah, that indeed sounds reasonable. Let me write another mod.

**Comment by alexandernst** [comment]
Now you have a new mod in `6.3.1` which should do exactly what you want.

**Comment by JihadMotii-REISys** [comment]
:+1:
