### ISSUE TITLE
Bug with first nested node/leafs

### ISSUE THREAD

**Issue by JihadMotii-REISys** [alexandernst/angular-multi-select#85]
I found a bug that occurs only to the first element that has sub items, e.g
- B
  - C

if I checked "B", the "C" won't be checked and if "C", the "B" won't checked neither the count of chekced items is considered.

Please see below this example

http://plnkr.co/edit/COAPdyHzwbRKdfUBwzYV?p=preview

**Comment by alexandernst** [comment]
You're absolutely right, and your plnkr helped a lot!
This should be fixed in `6.3.1`.

**Comment by JihadMotii-REISys** [comment]
:+1:
