### ISSUE TITLE
Lazy load

### ISSUE THREAD

**Issue by JihadMotii-REISys** [alexandernst/angular-multi-select#87]
Is there a feature for loading children nodes on demand ?

I have a dataset of +250K nodes to show and they're nested. It would be great if we have an option where to load only parents in the beginning and once we click on a parent node -> we load it's children and if it happens these childrens has subChildren, we do the same ...
What do you think ?

**Comment by alexandernst** [comment]
When you say `load`, what do you mean exactly? Attach items to the DOM?
If so, only the "visible" items are attached to the DOM in each operation. For example, if you have only 1 node and 34598672345698235692362938923569822346892376 leafs, if the node is closed, only 1 element (that node) will be attached to the DOM. There is no need of any type of lazy loading in there.

Does that answer your question?

**Comment by JihadMotii-REISys** [comment]
What happens right now is the browser gets so slow and it seems cannot handle large datasets to render it. my suggestion was loading only parents and have this component to render it and when you click on a parent node, an ajax call will be made to load it's children and append it to that parent node...

**Comment by alexandernst** [comment]
Ah, so you want to partially load items via ajax...

I'm not really sure how would that work. How do you expect to use such a feature? I mean, how would you configure it? Can you come up with how you expect the directive (the view) to look like when this is used?

**Comment by JihadMotii-REISys** [comment]
Exactly.

Here is an example of configuration:
`<div ...
angular-multi-select
input-model="dictionary.aAgency"
output-model="formHolder.aAgency"

**lazy-load = "true"
on-expand = "callbackFunctionLoadChildren"**`

This Method should be defined in the scope of the controller and should have parameters, one of them is the expanded node, e.g:
 `
// Controller
$scope.callbackFunctionLoadChildren = function(expandedNode, context, param3, param4, ...) {
//API Call children....
....then(function(aResult){
       expandedNode.$model.children = aResult; // assign children to the parent node (expanded node)
       context.notify(aResult); //Invoke notify to your context to render the children (only if needed) 
    });
}
`
Again, you can adjust it as you want ...

Please take a look at this just to give you an idea...
http://ca77y.github.io/2014/02/09/yet-another-angular-treeview-use-cases/

**Comment by alexandernst** [comment]
So... just skipping everything, this could actually work if the directive emitted some sort of event catchable from the controller?

Basically, your idea could work if the directive emitted signals to the rootScope, like this:

$rootScope.on("ams-open-node", function (ams-instance, node) {
    //check node id here, then fetch required data...
    //modify input model with the result of the ajax request
});

Am I right?

**Comment by JihadMotii-REISys** [comment]
That's correct !

**Comment by alexandernst** [comment]
@JihadMotii-REISys  Sorry for taking so long to implement this. I'll release v7 in an hour, I just need to finish updating the docs.
