### ISSUE TITLE
Get a number of selected nodes + parents

### ISSUE THREAD

**Issue by AlekseyKovalevsky** [alexandernst/angular-multi-select#89]
Hello Alex,
Is it possible to get a number of selected nodes + a number of parents? 
![image](https://cloud.githubusercontent.com/assets/12997256/14346924/1d2f2e48-fcbd-11e5-921d-4315b22a290c.png)

**Comment by alexandernst** [comment]
Do you want the button label to count only the fully-checked nodes or any node that isn't unchecked?

**Comment by AlekseyKovalevsky** [comment]
I want to count any node that isn't unchecked

**Comment by alexandernst** [comment]
I just updated the docs (`button styling` section). Please check it and close the issue if you think that solves your problem.

**Comment by AlekseyKovalevsky** [comment]
Great! Thank you.
