### ISSUE TITLE
Search doesn't work with angular 1.3.*

### ISSUE THREAD

**Issue by AlekseyKovalevsky** [alexandernst/angular-multi-select#90]
Hello, Alex!

I have found that search does not work with angular 1.3.*.
The problem is in`$timeout` function :

```
self.search_promise = $timeout(function (query) {
                        //TODO: this needs a lot of improving. Maybe use lunar.js?
                        var filter = [];
                        filter.push({
                            field: $scope.search_field,
                            query: query
                        });

                        $scope.items = amse.get_filtered_tree(filter);
                        $scope.search_spinner_visible = false;
                    }, 1500, true, _new);
                });
```

Angular's old version of `$timeout` doesn't support additional parameters to the executed function, therefore `_new` parameter is not used and `query` has undefined value. 
[ docs for $timeout's old version](https://code.angularjs.org/1.3.19/docs/api/ng/service/$timeout)
[ docs for $timeout's current version](https://docs.angularjs.org/api/ng/service/$timeout)

Do you have any ideas how to fix it with angular 1.3.\* ? 
And if you don't have, is it possible to customize search ( use my own custom search)?

**Comment by alexandernst** [comment]
Doesn't look like a hard one to fix. Give me a few hours.

**Comment by alexandernst** [comment]
I'll release v7 in a few hours, you can use that one. Please read the upgrading docs as some things changed.

**Comment by AlekseyKovalevsky** [comment]
Thank you so much :)
