### ISSUE TITLE
Artifact not available through Bower

### ISSUE THREAD

**Issue by blabno** [alexandernst/angular-multi-select#99]
Why this awesome frontend lib is not hosted on bower?

**Comment by alexandernst** [comment]
I have extremely bad experiences with Bower...
Are you willing to make a PR to add support for it?

Only rule when adding bower support is: do not change the way things work now. Bower shouldn't be required for the library to be installed via NPM, nor it should be required at any stage of the process if the user isn't using Bower itself explicitly.

**Comment by blabno** [comment]
https://github.com/alexandernst/angular-multi-select/pull/100
